version: '2'

services:
  jupyterlab-docker:
    image: casewareint/jupyterlab-docker:latest
    container_name: jupyterlab-docker
    ports:
      - 8888:8888
    volumes:
      # so that files in container persist
      - .:/app